### ISSUE TITLE
Allow custom sorting

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#10]
Contributors can setup content to be sorted based on data (front matter) so that content doesn't need to be sorted by hand.

**Comment by bechatman** [comment]
@gregoryjscott This issue has shown to be more important than I thought for some of the pages that I am working on. What I am thinking is maybe a new liquid tag that can handle sorting? 

Here's the scenario I am dealing with:

* I have a CSV in the _data folder that is loading entries across many board pages.
* Each board page must show documents from this, but it has to be limited to 12 per board (not time-based but meeting instances)
* The items needs to be sorted by their post date, but they may not be in the CSV file in that order.

What I am envisioning as a possible solutions is something like this:
```
{% for item in site.data.board-decisions %}
{% if item.tags contains "zoningcommission" %}
{% sort item.date direction:descending limit:12 %}
<li>...</li>
{% endsort %}
{% endif %}
{% endfor %}
```

**Comment by bechatman** [comment]
@gregoryjscott not sure if this should be in the sort tag or not (seems like it might be a good practice, but it may be mixing functionality) is there a way to have a default message if there are no items?

Using the site.data functionality means that main not return null unless they are completely blank, and if you have a bunch of filters, you need a check to see if there are any remaining items (requiring the check to be lower down). 

The use case for this would be on the calendar. If you sorted to show items that are before the end date and give it the `for_hours=24` attribute, you would want a message that "No events today" as the message if all items are filtered out. 

Since `sort` should be the last step, it seems like a "null message" might be attached to it, maybe inside it's own liquid tag `{% null_message %} text... {% endnull_message %}`.

**Comment by gregoryjscott** [comment]
I don't know. I'm starting to question the whole approach.

I think the liquid tags make sense in certain cases but not all. For example, I think the `before` tag works well if you want to display a paragraph of information before a certain date. However, trying to use it to filter a set of data based on a certain date is stretching it. It would be better to pre-process the data so that you would have `site.data.todaysEvents`, then all you have to do is check it's length (or for null). We can pre-sort it so that in most cases doing a sort in the page/layout won't be necessary. Additionally, the readability of your logic is improved since `site.data.todaysEvents` is self explanatory. Trying to determine the intentions of a bunch of `if`, `before`, `after`, and `null_message` logic is going to be confusing and hard to maintain in the long run.

I think we've been guilty of building solutions (e.g. the custom Liquid tags) without first identifying the problems we're trying to solve. We should identify all the data sets that are needed to produce the desired content, such as all events, today's events, upcoming events, etc. That will make it easier to make decisions on implementation.

**Comment by bechatman** [comment]
I get what you are saying, but being able to create new functionality by creating my own logic to deal with data in the system is the appeal of Jekyll. 

If we go the `sort` route, then I can build out new functionality and views (say an RSS feed that can be used to auto-populate an email). If we focus on de-normalized data pulling from external data sources, I dependent on a developer and back in the same boat I've been in since 07 with our current CMS.

Now, all of that said, maybe we could think outside of standard Jekyll/Liquid box. It could be that what really needs to happen is a replacement for the standard Liquid logic tools (think shadow DOM and web components versus a complex jQuery plugin with a ton of divs). 

Would something like this make more sense:

- `{% source item in site.pages | sortby:"variable" | before:"end_date" | after:"date" %}`
- `{% source item in site.data.features | before:"end_date" | sortby:"variable" reversed %}`
- `{% source item in site.posts | before:"end_date" %}`
- `{% source item in site.categories.services | before:"end_date" %}`

Something like this rolls all of the logic that I've requested into a new element that can tap the existing content APIs. It is a lot of filters, but I don't see a way around a lot of declarations unless you roll up the before/after logic into set boolean values like:

- `future:false` (this would be like the posts folder where items don't display until their "date" value.
- `ended:false` (this would follow the same logic as the publish date but apply to the end date.

This would be a much more opinionated approach to the variables, but that is very much in keeping with the way Jekyll works with Liquid. It also wouldn't replace before/after (especially since I am already using it throughout the site), but I could progressively replace `for` loops with something like this.

A variation on that approach could also come out of `null_message`. The only thing that stops me from  using an "if" statement is that most of the built-in content APIs won't return null until after we apply the logic. So, instead of replacing "for" and a chain of "if" statements, what if `source` defined a variable like `assign` or `capture`:
```
{% source dataSource1 in site.data.features | sortby:"variable" | direction:"ascending" | before:"end_date" | after:"date" %}
{% if dataSource1 != null %}
<h2>Heading</h2>
{% for item in dataSource1 %}
some template...
{% endfor %}
{% endif %}
```
Do either of these approaches sound better/easier?

**Comment by gregoryjscott** [comment]
I would argue that you are a developer when you are writing logic using Liquid. But I get your point, it's easier to just put the logic right in the page. I need to look at some real examples so that I can better understand the problems that are trying to be solved.

**Comment by bechatman** [comment]
Funny you should mention that, because I am about to post an example in the Roundup repo. Also, if you check out boards/zoningcommission. Also, if you look at any of the news and feature/alert/ad modules I have pulling from features.csv (like the test index page or the main page under codecompliance/keep-fort-worth-beautiful), all of those are cases where I am creating some kind of logic chain.

I will comment on the pull request in Roundup where you can see a much clearer example, though.

**Comment by bechatman** [comment]
Just tested out the assign sort capabilities and that is working great for me. If there is any way to get before/after in there as a filter, it would be even better. I think the only thing it probably couldn't solve is limiting the number of items in the array unless you can define objects via a filter as well. Example:

```
{% assign array = site.data.board-decisions | sort:"date" | after:"date" | before:"end_date" | split:"tags" %}
{% for item in array.tag-name limit:5 reversed %}
```

**Comment by gregoryjscott** [comment]
That does read pretty well. Limiting the array could be done with a `take` filter ("take" is a common name for it).

```
{% assign top_5 = site.data.board-decisions | sort:"date" | take:5 %}
```

I'll add some of these to jekyll-date_logic gem and you can try them out.

**Comment by bechatman** [comment]
Is there an order filter? Seems like applying take before the direction is set could be a problem.

**Comment by gregoryjscott** [comment]
Yes. I didn't realize that `limit:5` was a real thing in Liquid. Liquid is odd, I don't understand why `limit` and `reverse` aren't just array filters (like `sort`) instead of these special options of a `for` loop.

**Comment by bechatman** [comment]
Doesn't make sense to me either. Any reason we couldn't just move them as array filters? Have "order" and "take"?

**Comment by gregoryjscott** [comment]
We can.

**Comment by bechatman** [comment]
Just stumbled onto something that helps here. First the bad: I just tried to reverse and limit the number of items displayed in an array using the for loop, and it looks like "reversed" doesn't do anything until after the array is reduced to the "limit" number of items. 

The good part is that for loops can take an `{% else %}` tag to show a message if there are no items in the array. 

So, if you can get sort order and date logic into filters, we could limit in the for loop (instead of the take filter) and have a default message as well. This would only leave out one use case, which is when you are filtering on tags other than date inside the for loop and you want to limit the number displayed. I can't think of anywhere that could be an issue, though, so I think this is probably the best solution.

The only thing we really would need to verify would be if this line of code would work on posts if the date is explicitly stated in the file

```
{% assign news = site.categories.news | sort:"date" | order:"ascending" | before:"end_date" | after:"date" %}
<ul>
{% for item in news limit:5 %}
<li>{{ some kind of template }}</li>
{% else %}
<li>No items</li>
{% endfor %}
</ul>
```

**Comment by gregoryjscott** [comment]
It looks like Liquid contains a `reverse` array filter https://github.com/Shopify/liquid/blob/86a82d303989fa4afdbf2d8d15454c49f5b2df5c/lib/liquid/standardfilters.rb#L136-L140 already. @bechatman could you give it a try when you get a chance? If that works we don't need a custom `order` filter.

**Comment by bechatman** [comment]
Looks like that did the trick. Not sure why I didn't think that it would be a filter if it is available in a Liquid `for` loop, but good thinking. That also allowed me to limit decisions to one year's worth on the Zoning Commission page and limit the docket to display only the latest, so we just need before/after filters to handle most use cases. 

The only other use case would be to pass a variable (tags for example) and then a list of values that are acceptable. That is the most limited of all the use cases, though, so probably fine staying in `if` statements.

**Comment by gregoryjscott** [comment]
OK, #71 is merged and makes the `before` and `after` array filters available. I think that gives you everything you need for filtering and sorting except the tags and categories thing. I have an idea that I need to try for that.

**Comment by bechatman** [comment]
One more thought: How difficult would it be to add a second argument to the before/after filters that could use for_hours like sort uses the nils value?

**Comment by gregoryjscott** [comment]
The implementation won't be hard, just need to figure out the syntax. You can pass one or more strings to the filter. So would it look like this?

```
{% assign news = site.categories.news | before:"end_date","for_hours","24" %}
```

I can't say that I love that, but I could make it work.

**Comment by bechatman** [comment]
It could just be before:"end_date","24"




If the second parameter is always for_hours, that would take care of it.

**Comment by gregoryjscott** [comment]
Nobody outside of you and I would know what that 24 means. I don't think that is very readable. An perhaps we (or maybe others) will want to improve the usability of these filter/blocks with additional parameters like for_days, for_months, etc.

**Comment by bechatman** [comment]
That is true, but that is also true of the parameters on sort. Seems to be a theme in liquid. If it can't be passed together (e.g. Before:"end_date","for_hours:24"), it seems confusing to actually name it in the argument. If you can take that and split it at the colon, that would make it extensible and still make sense.

**Comment by gregoryjscott** [comment]
I like that better. I'll try it.

**Comment by gregoryjscott** [comment]
The only thing we have left now is the filtering pages by tags/categories.

**Comment by bechatman** [comment]
True, but I am wondering if maybe we should hold off on that for the time being. It sounds like that might be something that could be broken in the new structure of Jekyll 3.0 if the make everything work like collections. 

So, maybe close this for now and we can put in a new issue after 3.0 if the need is still there?

**Comment by gregoryjscott** [comment]
Sounds good to me. I'll close.
