### ISSUE TITLE
for_hours issue

### ISSUE THREAD

**Issue by bechatman** [cityoffortworth/FortWorthTexas.gov#56]
I attempted to implement the for_hours portion of `after` in the feature-test branch calendar on index.html. It looks like the extension from current time is extending the wrong direction, though, because setting it to 216 hours revealed Feb. 14, not something that happened on Feb. 28. 

And, just to make sure I am understanding the logic correctly, it basically says that any date you put in after will return true if the date is in the future compared to the current date, but adding the for_hours portion scopes it to within that number of hours from the current date,?

**Comment by gregoryjscott** [comment]
`after` with `for_hours` _should_ work just like `after` without `for_hours` accept that it effectively expires `for_hours` after the given time.

Let's say `page.start_date` is equal to `2015-03-01 00:00:00` and you have the following in your page.

```
{% after page.start_date for_hours=5 %}
  Hi
{% endafter %}
```

"Hi" would display between `2015-03-01 00:00:00` and `2015-03-01 05:00:00`, or in other words, after `2015-03-01 00:00:00` for 5 hours.

Is there an example of using `for_hours` in the `feature-test` branch? I didn't find one.

**Comment by bechatman** [comment]
Yeah, it should be on the index file in the root.

**Comment by bechatman** [comment]
That explanation does make sense, but it seems to be going the other direction (subtracting, not adding). That said, the way it is working should be attached to `before` and I think it will accomplish what I am looking to do. `after` with `for_hours` works if something has a start date, but no end date. It doesn't work if the item is on a date and needs to be displayed prior to that date.

**Comment by gregoryjscott** [comment]
The `after` block is working as it should and I agree that what you really want is a `for_hours` option for the `before` block. I have that ready in a gem that I'll push to the cityoffortworth organization. After it's there then we can push a commit here that switches to using the gem.

**Comment by bechatman** [comment]
I guess I am lost then. Why would the `after` pull something from Feb. 14? Your explanation said it returns true when the date you pass is between current time and the end of the `for_hours` period (forward from site time, not the variable). If it is able to pull something from the past, that means it is looking at the variable, not site time, and determining if it is that means hours from site time. 

The difference is that if you have a bunch of dates and you want anything that occurs after site time but no more than five hours from site time, that is not what you get. You anything where the variable is within five hours of site time AND everything that is after site time.

**Comment by bechatman** [comment]
The same would apply to the `before` behavior. If the same logic that pulled a Feb. 14 on `after` is applied, that means that it would return true if the date is before site time AND if it is within a certain number of hours after site time. It should only return true if the item is before site time and it is within x number of hours before site time.

**Comment by gregoryjscott** [comment]
It works like it reads.

`after page.start_date for_hours=216` will show content when "right now" is after page.start_date but only for 216 hours. In English, you would say "After page.end_date I want to start showing this, but I only want to show it for 216 hours". This is why the Feb. 14 date qualified when you entered this bug, Feb. 14th was after right now but still within 216 hours. (It's now been more than 216 hours since Feb. 14 so it doesn't show now).  This is consistent to how `after` works when you don't pass `for_hours`. The content shows when "right now" is after the page.start_date. Generally speaking, I would guess that `after` will mostly be used with "start dates".

`before` does the opposite.

`before page.end_date for_hours=216` will show content when "right now" is before page.end_date but only for 216 hours before the given page.end_date. I think this is what you want in your feature-test branch situation. `before` would likely work in "end date" situations.

**Comment by gregoryjscott** [comment]
The gem is going to need good documentation, obviously.

**Comment by bechatman** [comment]
I guess I am just not understanding how that would work, so check me on this: If I passed a calendar entry's `page.event_date` to `before for_hours=72` right now, it should return anything between right now `2015-02-25T12:42:00` and 72 hours from now `2015-02-28T12:42:00`. 

Likewise, if I wanted to keep calendar entries on the site after their event date, I would use `after` to return everything from 72 hours ago `2015-02-22T12:42:00` and right now `2015-02-25T12:42:00`.

If that is all correct, then I think I get it and the only thing that threw me off was not having `for_hours` on before.

**Comment by bechatman** [comment]
Oh, and if that is correct, can we just update the file to remote to the gem in the feature-test branch?

**Comment by gregoryjscott** [comment]
> I guess I am just not understanding how that would work, so check me on this: If I passed a calendar entry's page.event_date to before for_hours=72 right now, it should return anything between right now 2015-02-25T12:42:00 and 72 hours from now 2015-02-28T12:42:00.

Yes, if page.event_date is equal to 2015-02-28T12:42:00. It would show content **before** 2015-02-28T12:42:00 for 72 hours.

> Likewise, if I wanted to keep calendar entries on the site after their event date, I would use after to return everything from 72 hours ago 2015-02-22T12:42:00 and right now 2015-02-25T12:42:00.

Yes, if the page.event_date is equal to 2015-02-22T12:42:00. It would show content **after** 2015-02-22T12:42:00 for 72 hours (it would stop showing at 2015-02-25T12:42:00).

I think we should seriously consider renaming these blocks. I have to think really hard in order to explain it correctly. It shouldn't be this hard to understand how they work.

**Comment by gregoryjscott** [comment]
I can switch it to use the gem as soon as this is closed https://github.com/cityoffortworth/date-logic-for-jekyll/issues/1.

**Comment by bechatman** [comment]
Just double checking, but this issue can be closed now that I merged the feature-test branch, correct?

**Comment by gregoryjscott** [comment]
Yep.
