### ISSUE TITLE
Allow showing content based on date logic

### ISSUE THREAD

**Issue by gregoryjscott** [cityoffortworth/FortWorthTexas.gov#9]
Contributors can setup templates to display content based on data values (using front matter) so that content will be displayed on the appropriate pages (e.g. checking the "close date" in a purchasing post to determine if it should be on an "open" or "closed" bid page).

- [ ] Support UTC data format

**Comment by bechatman** [comment]
I tested out the output for end_date to see if it could be manipulated by liquid filters, and that worked great. I did, however, run into another issue where the built-in options can't output date/time in Associated Press style, like what we use on our site. Is it possible to add a task to create one of the custom filters (like the date_to_string ... maybe date_to_AP and date_to_AP_time), or would that need to be an additional issue I should open for consideration down the road? 

These are the requirements:

* Meridian indicators should be a.m. and p.m.
* Time should output in 12-hour format, but ":00" should be omitted on the hour, and noon and midnight should be spelled out (i.e. 1 p.m. 1:30 p.m. but no meridian indicator on noon or midnight). 
* March through July should be spelled out, but August through February should be abbreviated. The September abbreviation should be Sept. instead of Sep.
* The overall format should like like these examples
  * noon Feb. 12, 2015
  * 1:30 p.m. Feb. 22, 2015
  * 8 a.m. Feb. 24, 2015
